"""Add loan fields

Revision ID: c815c34bb891
Revises: 
Create Date: 2025-07-14 17:00:55.864013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c815c34bb891'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expense')
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_type', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('person', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('note', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entry', schema=None) as batch_op:
        batch_op.drop_column('note')
        batch_op.drop_column('person')
        batch_op.drop_column('loan_type')

    op.create_table('expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
